### ISSUE TITLE
keeps redirecting to restsocialexaple.com:8000 with my own facebook keys

### ISSUE THREAD

**Issue by jassi5887** [st4lk/django-rest-social-auth#1]
Hi,

Is there something I need to change to change this behaviour ? Please help.
I am using my own key and secret within my own app but after accepting facebook permissions or even when cancelling the process it keeps me redirecting to restsocialexample. Please let me know what needs to be changed and where, 

Thanks a lot.
Jatinder

**Comment by st4lk** [comment]
Hi jassi,

please tell, what url your server is running at?
By default, django-rest-social-auth will take current server url and use it for redirect.

**Comment by jassi5887** [comment]
Hey,

Thanks for replying. I looked everywhere but in the html file that's where it was getting redirected to your example url on the last script. I changed it and it worked.

Cheers
Jatinder

-----Original Message-----
