### ISSUE TITLE
Cross Client ID possible?

### ISSUE THREAD

**Issue by eigenmannmartin** [st4lk/django-rest-social-auth#103]
I was unable to use social/token endpoint for google with different client-ids for backend and application
```requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://accounts.google.com/o/oauth2/token```

Is it even possible to that?

Thank you for your awesome work and the time invested!

**Comment by st4lk** [comment]
Hi Martin,

have you tried example_project from this repo (it has google auth)?

**Comment by eigenmannmartin** [comment]
yes - the error is not from this library as far as I can tell.
It originates in `social_core/utils.py:256`

I am using a different client id when retrieving the code as in the backend.
I am not sure if that is even possible or if I need to use the id_token?
