### ISSUE TITLE
Facebook jwt auth is not working properly (in the example project)

### ISSUE THREAD

**Issue by NotSoShaby** [st4lk/django-rest-social-auth#104]
I cloned the repo and followed instructions, but still Facebook login shows this: 

![image](https://user-images.githubusercontent.com/26500236/69609068-61e41180-1031-11ea-9db6-2a6ef49b5511.png)

the site then has a pop-up: 
Something went wrong, maybe you haven't installed 'django-rest-framework-simplejwt'?

needless to say, i do have djangorestframework-simplejwt installed

Any ideas?

**Comment by st4lk** [comment]
Thanks for spotting this out.
I've submitted a fix, try to follow updated instructions:
https://github.com/st4lk/django-rest-social-auth#example

In short, facebook app that is used in example project is in live mode (not in development).
Facebook requires HTTPS support in the website.

In updated instructions, it is written how to run 127.0.0.1 server with HTTPS.
