### ISSUE TITLE
Django 3 compatibility

### ISSUE THREAD

**Issue by mattLLVW** [st4lk/django-rest-social-auth#106]
Currently django-rest-social-auth has `django>=1.11,<3.0` as a requirement.
Could you change it so it can be compatible with Django 3?
Thank you!

**Comment by st4lk** [comment]
Thanks for reminded, I've added Django 3.0 support.

I will publish new version in pypi soon.

**Comment by st4lk** [comment]
Uploaded to pypi [v3.0.0](https://pypi.org/project/rest-social-auth/3.0.0/)
