### ISSUE TITLE
Remove django.conf.urls.patterns from code

### ISSUE THREAD

**Issue by Budulianin** [st4lk/django-rest-social-auth#11]
Need remove django.conf.urls.patterns, because it's deprecated.

**Comment by st4lk** [comment]
Fixed by #12

**Comment by Budulianin** [comment]
Was fixed and merged. Thanks

**Comment by st4lk** [comment]
Now in pypi [v0.4.2](https://pypi.python.org/pypi/rest_social_auth/0.4.2)
