### ISSUE TITLE
change  KnoxSerializer 

### ISSUE THREAD

**Issue by alikomijani** [st4lk/django-rest-social-auth#110]
Hi, when I use knox i get this error :

**Object of type 'AuthToken' is not JSON serializable**
so you must change token value from  AuthToken.objects.create(obj) to AuthToken.objects.create(obj)[1]
beacause AuthToken return a tuple and you need just token

class KnoxSerializer(TokenSerializer):
    def get_token(self, obj):
        try:
            from knox.models import AuthToken
        except ImportError:
            warnings.warn('django-rest-knox must be installed for Knox authentication', ImportWarning)
            raise
        **token = AuthToken.objects.create(obj)[1]**
        return token

**Comment by st4lk** [comment]
Fix is published in [v4.0.0](https://pypi.org/project/rest-social-auth/4.0.0/) now.
