### ISSUE TITLE
How can I test this for Google also?

### ISSUE THREAD

**Issue by aniketmaithani** [st4lk/django-rest-social-auth#13]
i want to test it for Google Oauth

**Comment by st4lk** [comment]
Hi Aniket!
In [example project](https://github.com/st4lk/django-rest-social-auth/tree/master/example_project) there is authentication using Google OAuth2.0. Or you need something else?

**Comment by aniketmaithani** [comment]
@st4lk  it was a mistake on my part, I messed up my configuration. All working fine now. Thanks to you example project. you can close this now

**Comment by st4lk** [comment]
Ok
