### ISSUE TITLE
TypeError in django-rest-social-auth/rest_social_auth/views.py at line 225

### ISSUE THREAD

**Issue by sputnik5459** [st4lk/django-rest-social-auth#144]
in `message = error.response.json()['error']['message']` error.response.json()['error'] not always returns dict. As I understand, sometimes it's a string, so, code breaks with TypeError: string indices must be integers. You should add types handling.

**Comment by st4lk** [comment]
Fixed by https://github.com/st4lk/django-rest-social-auth/pull/145

**Comment by st4lk** [comment]
Available in pypi: https://pypi.org/project/rest-social-auth/6.0.1/
