### ISSUE TITLE
Django 4 support

### ISSUE THREAD

**Issue by alex-pobeditel-2004** [st4lk/django-rest-social-auth#153]
Hello!
Django 4.0 is out but this project pins Django version to `<4.0` and prevents upgrade.

I tried to run `make test` locally to check if it will work "as is" but I keep getting errors during `pip install` phase - like these:  
`ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '//django_rest_social_auth/venv/lib/python3.7/site-packages/typing_extensions.py'`
I don't know if these errors are caused by this strange `//` in the beginning of the path or by some environment mismatch (I tried on Arch Linux, Docker 20.10.12) and I failed to make it work.

Maybe you can check if it works with 4.0?  `social-core` and `social-app-django` work with Python 3.10 / Django 4.0 so I think there are chances that your package is already compatible too.

**Comment by alex-pobeditel-2004** [comment]
I managed to run tests with WSL and at least one problem showed up: existing bugfix in django-rest-knox needs to be released (https://github.com/James1345/django-rest-knox/issues/260) but the repository seems to be not maintained anymore.  
So update to Django 4.0 (and Python 3.8+) is impossible at the moment :(

**Comment by JulesVR** [comment]
Hi @st4lk 
Would it be possible to create a release for django 4.0? django-rest-knox has been updated.
Thanks

**Comment by alex-pobeditel-2004** [comment]
@JulesVR knox with bugfix is [still not released](https://github.com/James1345/django-rest-knox/issues/260)

**Comment by JulesVR** [comment]
> @JulesVR knox with bugfix is [still not released](https://github.com/James1345/django-rest-knox/issues/260)

Sorry, mislooked. Thanks.

**Comment by alex-pobeditel-2004** [comment]
And hooray - knox bugfix was just released :)  
https://github.com/James1345/django-rest-knox/releases/tag/4.2.0  
@st4lk can you please try to create release for Python 3.10 / Django 4.0 now?

**Comment by spapanik** [comment]
Are there any updates on that?

**Comment by sevdog** [comment]
Is there an ETA for when this project will be compatible with Django 4.0?

**Comment by tuergeist** [comment]
@KOliver94 do you mind releasing your "next" branch as "rest-social-auth-ng"? 
It seems that this project went into deep sleep.
Otherwise I'd take you changes to make a release.

**Comment by KOliver94** [comment]
@tuergeist go for it, thanks! 🙂

**Comment by sevdog** [comment]
@st4lk are you going to provide any update to this project?

**Comment by st4lk** [comment]
Available in [pypi v8.0.0](https://pypi.org/project/rest-social-auth/8.0.0/)

**Comment by alex-pobeditel-2004** [comment]
@st4lk Thank you very much!
