### ISSUE TITLE
django/email-pwd signup/login support

### ISSUE THREAD

**Issue by shantanugoel** [st4lk/django-rest-social-auth#16]
Your project is very nice and working great for me for FB login. However, wanted to check if it'd be possible for you to add native django (email/password based) singup/login support as well to the project?

**Comment by st4lk** [comment]
Thanks, Shantanu!
Currently i think, that we shall not include email/password login in this package. It can be done easily with   just django rest framework. This package is focused on social auth only.

**Comment by shantanugoel** [comment]
No problem and thanks for taking the time to respond. :)
Will close this.
