### ISSUE TITLE
Getting an Immutable queryDict error in rest_social_auth/views.py line 118

### ISSUE THREAD

**Issue by shubh3794** [st4lk/django-rest-social-auth#17]
Hey! 
I am getting a querydict error : request QueryDict is immutable on posting from angular to django.
On further investigating i realized that in rest_social_auth/views.py line 118, request is being modified by the view which is not permitted.
How to get around this error!

**Comment by st4lk** [comment]
Hi shubham, thanks for reporting!

Looks like a bug. I suppose method `BaseSocialAuthView.get_serializer_in_data` must return copied data, not QueryDict itself. We need a patch here.

**Comment by shubh3794** [comment]
That would do it! 
I am facing one more issue, A user signs up to his fb account and then logs out. This creates his user entry in the user model. However if that user logs out and tries to log in again,  It creates a new user with a weird username. Like ShubhamAggarwal is the username for the user who logs in for the first time.  If he logs out and tries to log in again, A new user is created with username ShubhamAggarwal121532783def210_32 which is just very weird.

**Comment by st4lk** [comment]
I'm closing it, thanks again.
Now in pypi [v0.4.2](https://pypi.python.org/pypi/rest_social_auth/0.4.2)
