### ISSUE TITLE
Support for Django 5.1?

### ISSUE THREAD

**Issue by scribejourdan** [st4lk/django-rest-social-auth#178]
We're aiming to upgrade Django to 5.1 as it introduced database connection pools and we're using Poetry to manage our dependency tree.

Poetry points out that this package only supports 5.0.

> Because rest-social-auth (8.3.0) depends on django (>=3.2,<5.1)
 and no versions of rest-social-auth match >8.3.0,<9.0.0, rest-social-auth (>=8.3.0,<9.0.0) requires django (>=3.2,<5.1).
So, because non-package-mode depends on both Django (5.1) and rest-social-auth (^8.3.0), version solving failed.

**Comment by st4lk** [comment]
Thanks to @jourdanrodrigues, Django 5.1 is supported now:
https://pypi.org/project/rest-social-auth/8.4.0/

**Comment by st4lk** [comment]
If there are any problems with support, please reopen.
