### ISSUE TITLE
AssertionError at /api/login/social/token/

### ISSUE THREAD

**Issue by yonkornilov** [st4lk/django-rest-social-auth#20]
AssertionError at /api/login/social/token/

'SocialTokenOnlyAuthView' should either include a `queryset` attribute, or override the `get_queryset()` method.

Traceback:

Environment:

Request Method: GET
Request URL:

Django Version: 1.8.9
Python Version: 3.4.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'rest_framework.authtoken',
 'djoser',
 'accounts',
 'social.apps.django_app.default',
 'rest_social_auth')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')

```
Traceback:
File "/home/ubuntu/django-1.8-virtualenv/venv/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/ubuntu/django-1.8-virtualenv/venv/lib/python3.4/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)
File "/home/ubuntu/django-1.8-virtualenv/venv/lib/python3.4/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)
File "/home/ubuntu/django-1.8-virtualenv/venv/lib/python3.4/site-packages/rest_framework/views.py" in dispatch
  466.             response = self.handle_exception(exc)
File "/home/ubuntu/django-1.8-virtualenv/venv/lib/python3.4/site-packages/rest_framework/views.py" in dispatch
  454.             self.initial(request, *args, **kwargs)
File "/home/ubuntu/django-1.8-virtualenv/venv/lib/python3.4/site-packages/rest_framework/views.py" in initial
  377.         self.check_permissions(request)
File "/home/ubuntu/django-1.8-virtualenv/venv/lib/python3.4/site-packages/rest_framework/views.py" in check_permissions
  318.             if not permission.has_permission(request, self):
File "/home/ubuntu/django-1.8-virtualenv/venv/lib/python3.4/site-packages/rest_framework/permissions.py" in has_permission
  116.             queryset = view.get_queryset()
File "/home/ubuntu/django-1.8-virtualenv/venv/lib/python3.4/site-packages/rest_framework/generics.py" in get_queryset
  67.             % self.__class__.__name__

Exception Type: AssertionError at /api/login/social/token/
Exception Value: 'SocialTokenOnlyAuthView' should either include a `queryset` attribute, or override the `get_queryset()` method.
```

I'm not sure what is causing this. I am using:

python 3.4.3
django 1.8.9
djangorestframework 3.3.2
python-social-auth 0.2.14

**Comment by st4lk** [comment]
Hi Yonatan,
thanks for report.

Am i right, that you are using one of these: [`DjangoModelPermissions`](http://www.django-rest-framework.org/api-guide/permissions/#djangomodelpermissions) or [`DjangoModelPermissionsOrAnonReadOnly`](http://www.django-rest-framework.org/api-guide/permissions/#djangomodelpermissionsoranonreadonly) or [`DjangoObjectPermissions`](http://www.django-rest-framework.org/api-guide/permissions/#djangoobjectpermissions) ?

**Comment by yonkornilov** [comment]
Hmmm, didn't really know about those. I'll get back to you when I try again after looking into those permissions. Thank you

**Comment by yonkornilov** [comment]
I've tried defining those permissions in my app's settings.py. However this yields the same error.

**Comment by yonkornilov** [comment]
I misunderstood your response. I've removed the permissions you've mentioned and now my project works with the URLs from rest-social-auth. Thank you. Perhaps this should be mentioned in documentation though?

**Comment by st4lk** [comment]
No, this is a bug. It is absolutely normal to use those permission classes. We'll need a patch here.

**Comment by st4lk** [comment]
Now in [pypi v0.4.3](https://pypi.python.org/pypi/rest_social_auth/0.4.3)
