### ISSUE TITLE
Permissions should be AllowAny by default?

### ISSUE THREAD

**Issue by chozabu** [st4lk/django-rest-social-auth#21]
Hey, I feel I may be missing something obvious here, but looking at `SocialTokenOnlyAuthView` there is no permission class? as this is for login, should it not be default?

**Comment by st4lk** [comment]
Hi, from django rest framework [docs](http://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy):

> 
> If not specified, this setting defaults to allowing unrestricted access:
> 
> 'DEFAULT_PERMISSION_CLASSES': (
>    'rest_framework.permissions.AllowAny',
> )

So by default we have AllowAny permissions, no need to specify it explicitly

**Comment by chozabu** [comment]
I see - though I have changed my default permissions, and imagine many other people do too.
For a login - we always want `AllowAny`, so I think it makes more sense for DRSA to specify it explicitly

**Comment by st4lk** [comment]
Well, i think you are right.
Good spot, thanks! I'll make the changes in issue #20

**Comment by chozabu** [comment]
Glad to help - I've actually ended up duplicating the view in my app code for some other reason, will try and find out why and send a PR if needed at some point

**Comment by erickmendonca** [comment]
I had the same problem. I did the workaround by creating a new viewset that extends the rest-social one.

**Comment by chozabu** [comment]
@erickmendonca yes - that is a sensible workaround (I took the less sensible option of duplicating the whole class!)

**Comment by st4lk** [comment]
All work will be in issue #20
