### ISSUE TITLE
Errors from facebook are not returned or printed

### ISSUE THREAD

**Issue by chozabu** [st4lk/django-rest-social-auth#22]
in facebook.py, around line 73 there is the code:

        response = self.request(self.ACCESS_TOKEN_URL, params={
            'client_id': key,
            'redirect_uri': self.get_redirect_uri(state),
            'client_secret': secret,
            'code': self.data['code']
        })
        # API v2.3 returns a JSON, according to the documents linked at issue
        # #592, but it seems that this needs to be enabled(?), otherwise the
        # usual querystring type response is returned.

my initial problem was a non-matching redirect_uri  - but the error given was something like "auth cancelled"

after sending the correct URI, I still had the same "auth cancelled error" - though the actual error was an expired token

only by stepping through the code, then altering to:

        response = self.request(self.ACCESS_TOKEN_URL, params={
            'client_id': key,
            'redirect_uri': self.get_redirect_uri(state),
            'client_secret': secret,
            'code': self.data['code']
        })
        print("response", response)
        # API v2.3 returns a JSON, according to the documents linked at issue
        # #592, but it seems that this needs to be enabled(?), otherwise the
        # usual querystring type response is returned.

was I able to find the actual error

    response {'error': {'code': 100, 'fbtrace_id': '<removed>', 'type': 'OAuthException', 'message': 'This authorization code has expired.'}}

Perhaps I am missing something, but returning these errors would be great!

**Comment by st4lk** [comment]
Hi Alex,

Agree, we need some error logging. There is a method [`respond_error`](https://github.com/st4lk/django-rest-social-auth/blob/master/rest_social_auth/views.py#L170), it is called when some error happened during OAuth signin. This method accept error as argument, but this error is not logged anywhere. We can log this error using python logging for example.

The error is not returned in http request because i it can contain some private information.

**Comment by st4lk** [comment]
It is not so easy to get details because [python-social-auth](https://github.com/omab/python-social-auth) doesn't provide them.
I've create a [pull request](https://github.com/omab/python-social-auth/pull/883).
Let's see what maintainers of python-social-auth will say.

**Comment by chozabu** [comment]
Bit slow in checking my mail - but I see your PR was already accepted! fantastic :)

**Comment by st4lk** [comment]
I've added some code to log the errors.
But we need to wait until python-social-auth changes will be uploaded to pypi :)

**Comment by st4lk** [comment]
Now in pypi [v0.4.4](https://pypi.python.org/pypi/rest_social_auth/0.4.4)

**Comment by chozabu** [comment]
Hmm, I've just updated - but am still not sure how to get back the error returned from facebook

**Comment by st4lk** [comment]
Method [BaseSocialAuthView.respond_error](https://github.com/st4lk/django-rest-social-auth/blob/v0.4.4/rest_social_auth/views.py#L172) logs the error.
So the error shall be present in logs (maybe it is needed to configure it in settings.py).
Or you can override this method and process the error by yourself.
Does it help?

**Comment by chozabu** [comment]
Ahh, yes I see - the error is in error.response.error - fantastic!

I've overridden with:

    from rest_social_auth import views as social_views
    
    class BaseSocialAuthView(social_views.BaseSocialAuthView):
    
        def respond_error(self, error):
            l.exception(error)
            if isinstance(error, Exception):
                self.log_exception(error)
            else:
                l.error(error)
    
            emsg = error.response.content
            print(emsg)
            
            if default_settings.DEBUG:
                return Response(str(emsg), status=status.HTTP_400_BAD_REQUEST)
            return Response(status=status.HTTP_400_BAD_REQUEST)

And now get really easy error reporting in debug mode, and should still be safe in production

**Comment by chozabu** [comment]
note - I probably do not have the right setup for this to log correctly, I'll check it out in more detail

I suspect this:

        if default_settings.DEBUG:
            return Response(str(error.response.content), status=status.HTTP_400_BAD_REQUEST)
        return Response(status=status.HTTP_400_BAD_REQUEST)

or something similar may be a nice addition to trunk

**Comment by st4lk** [comment]
Year, good idea to respond the error in debug mode!
I've created new issue #26 for this
