### ISSUE TITLE
Mobile auth flow using rest social auth

### ISSUE THREAD

**Issue by shubh3794** [st4lk/django-rest-social-auth#23]
Hello, I am using rest social auth for angular and django web app, but now I want to implement mobile login for facebook and google.
Can anybody help me with this?

**Comment by abhijit838** [comment]
I am also trying the same with angular project. Please any help?

**Comment by coler-j** [comment]
@shubh3794 did you figure this out?

**Comment by abhijit838** [comment]
Hi @coler-j, I faced the same problem when I was trying to implement REST social auth in Python REST as well as well as in C# NancyFX . But there are different approaches out there. https://digitalleaves.com/social-login-for-your-rest-api-using-oauth-2-i/
above link is a very good article about social auth. And also each social auth provider has SDKs. 
I would prefer to use SDK then provide backend REST URL to persist user details and keep public token in the mobile client for later social media operation. Generate a token(if the backend is using token based auth) against the user credential to authenticate backend resources.

Still, I am not sure about the token timeout....

**Comment by st4lk** [comment]
This doesn't looks like an issue with this package, so I'm closing it.
