### ISSUE TITLE
Unable to fetch the google avatar

### ISSUE THREAD

**Issue by pnagle** [st4lk/django-rest-social-auth#27]
I wanted to include the avatar from google but the test example here (restsocialexample.com:8000) doesn't include the google avatar. 
The below snippet shows that it takes defualt gravtar for google too.
 social_thumb = None
        if 'facebook' in backend_name:
            if 'id' in response:
                social_thumb = ("http://graph.facebook.com/{0}/picture?"
                    "type=normal").format(response['id'])
        elif 'twitter' in backend_name and response.get('profile_image_url'):
            social_thumb = response['profile_image_url']
        else:
            social_thumb = "http://www.gravatar.com/avatar/"
            social_thumb += hashlib.md5(user.email.lower().encode('utf8')).hexdigest()
            social_thumb += "?size=100"

As there is no if condition for google. Can you help me in getting the google's thumbnail image url?

Thanks

**Comment by st4lk** [comment]
Hi, i've updated the code for [example project](https://github.com/st4lk/django-rest-social-auth/blob/master/example_project/users/social_pipeline.py#L21):

    elif 'googleoauth2' in backend_name and response.get('image', {}).get('url'):
        social_thumb = response['image']['url'].split('?')[0]

Does it help?

**Comment by pnagle** [comment]
That helps, works like a charm. Thanks
