### ISSUE TITLE
can not get example project working

### ISSUE THREAD

**Issue by musicformellons** [st4lk/django-rest-social-auth#30]
I tried twice setting it up, but when pressing the button "login facebook (oauth2)" of JWT, I keep getting the error:
"Something went wrong, maybe you haven't installed 'djangorestframework-jwt'?"

Which I have installed. Furthermore I followed all instructions closely it seems.

Couple of things I mention just to be clear (at this stage I am focusing on Facebook...):
1. In the settings there is a string set for SOCIAL_AUTH_FACEBOOK_KEY which I altered to my own facebook app key; and I did the same in the templates (bit suprised to find these there as well); obviously I also altered the secret key in settings.
2. My local server succesfully serves at http://restsocialexample.com:8000/  furthermore in the facebook app settings of mine I put these for redirect uri's:
   ![screenshot from 2016-09-08 17-52-21](https://cloud.githubusercontent.com/assets/10334123/18356733/3fdd9204-75ee-11e6-871f-07b143ae7f4f.png)
3. Furthermore this is the output in my browser console:
   Failed to load resource: the server responded with a status of 404 (NOT FOUND)
   http://restsocialexample.com:8000/api/login/social/jwt_user/facebook Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
   (index):121 Object
   (index):122 Something went wrong, maybe you haven't installed 'djangorestframework-jwt'?

Any help would be appreciated!

EDIT:
After reading docs another time it becomes now clear that I should leave the app ids and secrets 'as is' and not use my own (yet). Then Google JWT button works! But Facebook and Twitter both fail with same error message (see above). Google also works for session and token, others also not working...

For Facebook I made another testuseraccount; With that user I got the approval screen and I could continue to approve giving my email; after approval I get old errormessage again. The facebook account I use I also use in real live for login in all kinds of oauth2 authentication platforms, so should work...

**Comment by st4lk** [comment]
Thanks @musicformellons for noticing it. I also have troubles with facebook and twitter in example project. I'll try to figure out why.

**Comment by musicformellons** [comment]
Any progress on this?

**Comment by st4lk** [comment]
Sorry for not responding.
Currently, I'm very busy with my work, not sure when will have time for this.
But it is on my todo list :)

**Comment by st4lk** [comment]
BTW, if you have any idea how to fix it, PR is welcome.

**Comment by st4lk** [comment]
- Facebook issue fixed by #38 (added `SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS` setting)
- Twitter issue fixed by adding email permissions in twitter app: ![rest_social_auth_example_app twitter application management 2017-01-04 08-55-35](https://cloud.githubusercontent.com/assets/1771042/21632894/9d3ce49e-d25b-11e6-801c-6c3b3ce2a175.png)
