### ISSUE TITLE
Upgrade to django 1.10

### ISSUE THREAD

**Issue by BenDevelopment** [st4lk/django-rest-social-auth#32]
Hello,

Do you plan to upgrade to Django 1.10 in a near futur ?

**Comment by st4lk** [comment]
Hi, Benjamin!
I'll try to do it in nearest future, but not sure when. Currently very busy on my work.

**Comment by st4lk** [comment]
Is closed by #33
I'll upload to pypi soon

**Comment by st4lk** [comment]
Finally uploaded to [pypi](https://pypi.python.org/pypi/rest_social_auth) v1.0.0
