### ISSUE TITLE
Token User view returning 400 when on all environments but development

### ISSUE THREAD

**Issue by arol** [st4lk/django-rest-social-auth#36]
I've installed rest-social-auth in my django project and all were fine until now that I'm deploying it to production. Specifically, the request `…/social/token_user/` always responds a 400 on any environment that's not development.

I checked the settings for special configuration on development and I found nothing. I don't know how to debug this.

**Comment by st4lk** [comment]
Hi Arol,
Can you provide a response body?

**Comment by st4lk** [comment]
Maybe this #38 can help.
I saw a 400 response with body
```
{"error":"Email wasn't provided by facebook"}
```
for `/api/login/social/token_user/facebook`.
#38 solved it.

**Comment by arol** [comment]
Sorry for the delay, the authentication provider is Linked In. 

I left the constant `REST_SOCIAL_DOMAIN_FROM_ORIGIN` for mistake so I deleted it, now I'm passing it as a part of the payload on the request. Also I added the constant `REST_SOCIAL_DOMAIN_FROM_ORIGIN = False` on the settings.

It's working now :) sorry for the inconveniences, hope it helps somebody in the future.
