### ISSUE TITLE
How to test using a rest client ?

### ISSUE THREAD

**Issue by votaguz** [st4lk/django-rest-social-auth#4]
Hi, excuse me if  is a silly question but, how i can test login flow using a rest client ?
I'm trying to make a social registration flow, but i don't understand how to send the "code" parameter in the request payload. 

Thanks.

**Comment by st4lk** [comment]
Hi Jose,

you can send a POST request to /api/login/social/session/ with payload

    {
        "provider": "facebook",
        "code": "AQBPBBTjbdnehj51"
    }

To get the code from facebook manually, go to url (replace client_id and redirect_uri to your values): 

https://www.facebook.com/dialog/oauth?client_id=295137440610143&redirect_uri=http://restsocialexample.com:8000/

Please look at [facebook docs](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow) for details.

After confirmation you will be redirected back to redirect_uri, and code will be in GET params:

http://restsocialexample.com:8000/?code=AQBMRCdyj...

So you can use this code for testing (it will be valid only for one request).

Also, there is an [example_project](https://github.com/st4lk/django-rest-social-auth/tree/master/example_project), you can check, how it works.

**Comment by votaguz** [comment]
Hey thank you for answer. What about if i'm using Token authentication ? 

Thank you.

**Comment by st4lk** [comment]
Then use /api/login/social/token/ or /api/login/social/token_user/ url, they are described in [readme](../blob/master/README.md).

**Comment by votaguz** [comment]
Hey, I tried to follow the flow you described.
But when i try to make POST to the  /api/login/social/token/  url, i'm getting 400 [ BAD REQUEST ].
So, am i missing something, an HTTP Header or something like that ? 

I'm using PostMan App.

Thank you.

**Comment by st4lk** [comment]
It is hard to say, having just this information.
One suggestion is bad redirect_uri. It must be the same in both requests to OAuth provider: code request and access_token request. By default, django-rest-social-auth will use the domain it is working on as redirect_uri. And this redirect_uri must be the same, as you manually specified in code request.

Example:
- manually go to https://www.facebook.com/dialog/oauth?client_id=295137440610143&redirect_uri=http://restsocialexample.com:8000/ (note redirect_uri here is http://restsocialexample.com:8000/)
- run server on localhost:8000. As a result, server will use redirect_uri=http://localhost:8000, which is not the same, and you get 400 [BAD REQUEST].

**Comment by nikssardana** [comment]
Hey
I am having a similar problem in django 1.10.
If I go to `https://www.facebook.com/dialog/oauth?client_id=<client id>&redirect_uri=http://localhost:8000/`, it is working fine. But when I try to authenticate to Django using a token obtained by Javascript SDK, it shows Status 400 (Bad Request).
I am using Token Authentication and POSTing the following data on `http://localhost:8000/api/login/social/token/:`

`provider=facebook&code=<code here>`

I have even tried this:
`{ "provider": "facebook", "code": "EAADJVzOZAdnkBAM5wdnIlThWVyv27ZBb3tW8mpCB0edDuRQGuCafVnvCwgjOT6Oiascah5BpTIeRFATQiAFFMZA1RgKv9oueUQR04fFdA3cVPhzUAgzIZBUsqXaXL0u2uARN7QWCZAotTkryxrPh5boi1c5wZB4dpZChzgig5CX8sAuqQSb2usZB3nnu8Lhb0c8ZD" }`

The token is working fine if I try to access the graph API.

**Comment by Banashek** [comment]
Just as an FYI, I was getting a 400 when using httpie on the redirect request like you.

The solution was to add the sessionid cookie into the request.

**Comment by SalunMarvin** [comment]
I'm having the redirect_uri issue, but I can't find why!
At my OAuth2 specification to get Facebook's code, the Redirect URL is: `http://localhost:8000/api/login/social/token_user/`

Than I get the code, when I try to reach the URL, I get the error. And the URL I'm trying to reach is the same `http://localhost:8000/api/login/social/token_user/` with the body:

```{
  "provider": "facebook",
  "code": "AQAI0u0Pg0XJ_oSL-Ye_Lcv7JcVg67nrkms6SK93OF-UXKB5SYYmCQ6jWzu6x8c8rChbKQ2WT9pNqe0dlBsCZE3Eu3m1rtEhJSXkoVnXzp4v2E3EUGAl7LR_rJSLZOPQZc-LU_F07UvSOdJUnWbAExP2vYdjHviRpz4ic5BGPcCgM2HmJZjZJrc2Ym5rWgzogb7Xdv1qDkgkqlkAdKldnz73rYfiMPa0_EMatgSdjGfYRXl3AX-FGVD0BhG8XE1KdH1vpiDWakYNc_IVZDOAeOx1PKFqDojwmPUqq-imphz0KEbEjUOFs2TvR7HabZYvHZZbfYSY1webi3S6q2KQjBvEWacwR-MnTk9xHF8hMhv8rQ"
}```

Can't understand why!
