### ISSUE TITLE
make the logging of failed authentication requests optional using a configuration value

### ISSUE THREAD

**Issue by MounirMesselmeni** [st4lk/django-rest-social-auth#42]
Make logging of exceptions when social auth raise a ```AuthForbidden(AuthException)``` error optional.

```
        try:
            user = self.get_object()
        except (AuthException, HTTPError) as e:
            return self.respond_error(e)
```

**Comment by MounirMesselmeni** [comment]
See #43

**Comment by MounirMesselmeni** [comment]
I hope you can release that asap. And thanks for the merge.

**Comment by st4lk** [comment]
@MounirMesselmeni  Uploaded [v1.1.0](https://pypi.python.org/pypi/rest_social_auth/1.1.0)
