### ISSUE TITLE
Forbidden (403) CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by annshress** [st4lk/django-rest-social-auth#44]
Trying to use session based authentication from rest-social-auth. Cant figure a way to avoid csrf token validation.

**Comment by st4lk** [comment]
You need to send same value in header and in cookies:
https://docs.djangoproject.com/en/1.10/ref/csrf/#ajax

**Comment by annshress** [comment]
Thanks, your solution helps. But still, I keep getting 400 Bad request.

views.BaseSocialAuthView.post method keeps catching an AuthCanceled exception.

my post params has follows in body:
code:<facebook user access token>
provider:facebook
csrfmiddlewaretoken:<csrf token>

and request header has:
csrfmiddlewaretoken:<csrf token>

**Comment by st4lk** [comment]
Does example project works for you?

**Comment by annshress** [comment]
my settings.py extra configs
REST_SOCIAL_OAUTH_REDIRECT_URI = '/'
REST_SOCIAL_DOMAIN_FROM_ORIGIN = True

bad response:
ERROR:rest_social_auth.views: Authentication process canceled; ; {u'error': {u'message': u"redirect_uri isn't an absolute URI. Check RFC 3986.", u'code': 191, u'type': u'OAuthException', u'fbtrace_id': u'G27RnD9w5GC'}} (2017-02-20 09:11:47; views.py:193)

**Comment by ergusto** [comment]
Did you manage to get around the CSRF error?

**Comment by annshress** [comment]
Yes, it was issue related CORS.

For AJAX request, we used _credentials=true_ and send a _csrfmiddlewaretoken=<token>_ (that is actually received from the backend). While in the Django Backend. I used CORS_ALLOW_CREDENTIALS=True settings so that Cookie sent by the ajax request can be accepted by the server.

**Comment by Roko4u** [comment]
The same issue happens with me too. Whenever I try to post something, it shoes forhidden, enable cookies.

**Comment by st4lk** [comment]
Guys, I can't reproduce it with example project. Fill free to reopen if the issue still exists.
