### ISSUE TITLE
In documentation it shows "code" as one of the required properties

### ISSUE THREAD

**Issue by jfrux** [st4lk/django-rest-social-auth#45]
What is the "code" part supposed to be within this:

```
{
    "provider": "facebook",
    "code": "AQBPBBTjbdnehj51"
}
```

**Comment by st4lk** [comment]
@joshuairl 
It is Authorization Code in terms of [OAuth 2.0](https://tools.ietf.org/html/rfc6749#section-1.3.1)

**Comment by st4lk** [comment]
Have added it in readme

**Comment by nabeelayub** [comment]
I also didn't know how to get the code,can someone please give some explanation how to get it
