### ISSUE TITLE
Django 1.11 support?

### ISSUE THREAD

**Issue by half0wl** [st4lk/django-rest-social-auth#47]
Are there any side effects to using this in Django 1.11 by updating the dependencies (`social-auth-core==1.2.0` and `social-auth-app-django==1.1.0`)? As far as I can tell, the only error in Django 1.11 is due to python-social-auth/social-app-django#24, which is fixed by the latest releases of social-auth-core and social-app-django.

Related commit: b02f99f89321ea8f1f05468591d4f157d982ad49

**Comment by serdyuk-alex** [comment]
seems to work fine on django 1.11, I've pulled 1.1.0 tag version of lib and updated tox file in order to test with latest django social-auth-core and social-auth-app-django. test were ok

**Comment by tobias47n9e** [comment]
Related PR: https://github.com/st4lk/django-rest-social-auth/pull/54

**Comment by st4lk** [comment]
The lib should support Django 1.11.
If there are any errors regarding this, please reopen.
