### ISSUE TITLE
Difficulty undertanding  LinkedIn oauth2 flow

### ISSUE THREAD

**Issue by pedx78** [st4lk/django-rest-social-auth#48]
Having problem understanding  oauth2 flow on readme

https://github.com/st4lk/django-rest-social-auth#oauth-20-workflow-with-rest-social-auth
4. Social provider redirects back to redirect_uri with param code.

What is the redirect_uri ?
I am not sure what url to register with linkedin.
Is it generated by the plugin, or do I have to implement endpoint myself ?

How does one get the returned code ?
Does front end call the redirect_uri to retreive the code ?
Or server retrieves it and sends to front end ?

Hope above can be clarified

**Comment by st4lk** [comment]
@pedx78 
redirect_uri - is just a URI of your site, that will handle response from social provider. You can keep the default value (`/`), in that case it will be a root path of your site. Please check the [example](https://github.com/st4lk/django-rest-social-auth#example) project.
