### ISSUE TITLE
Authentication process canceled; Invalid verification code format.

### ISSUE THREAD

**Issue by veddermatic** [st4lk/django-rest-social-auth#50]
Attempting to get this to work and running into an error that is stumping me. (To be fair, that's not hard to do...)  I can log in / create users using "vanilla" `social-auth-app-django` and everything works, so that seems to be in order. 

When I attempt to use the API endpoints provided from here I get this error on the server side:

`ERROR:rest_social_auth.views: Authentication process canceled; ; {'error': {'code': 100, 'type': 'OAuthException', 'fbtrace_id': 'Ec2RsuzzbGD', 'message': 'Invalid verification code format.'}} (2017-07-20 17:20:19; views.py:193)`

The code I'm sending validates here: https://developers.facebook.com/tools/debug/accesstoken/ so I know that part is good. My request is being sent to:

`http://localhost:8888/api/login/social/jwt/facebook/`

with a body of:

`{
"code": "EAAT7bZB0BZ...2UZD"
}
`
(truncated for length, but again, the code validates on FB's tool)

Currently using these dependencies:

    Django==1.11.3
    djangorestframework==3.6.3
    djangorestframework-jwt==1.11.0
    social-auth-app-django==1.2.0
    social-auth-core==1.4.0
    rest-social-auth==1.1.0

Any thoughts?

**Comment by veddermatic** [comment]
So, it looks like when I log a user in via the Facebook javascript SDK, I get back an `accessToken` which is *not* a code.  So it seems I should just use `django-rest-auth` instead.

Closing since I guess I was doing something I am not supposed to!

**Comment by SalunMarvin** [comment]
Well, I'm getting the access code, but I can't find "code" anywhere. Did you managed how to do that?
