### ISSUE TITLE
401 - Signature has expired.

### ISSUE THREAD

**Issue by BrettStatman** [st4lk/django-rest-social-auth#53]
Hello,

I am trying to implement Facebook social auth with JWT. I am getting the `code` by going to `https://www.facebook.com/v2.10/dialog/oauth` with client_id and redirect_uri set. After successful authorization, I am redirected to the redirect_uri with a code - something that looks like this (much larger than what is in the docs)
```
    AQAfv3ihWevjXTnHYTQFAw1-0M-d-s7PMuZ3Uv7ngCMK9pyQUsprOCaF2iUkKQgSwmvOpK1v1NtoTNcC7Jn8xPPikrQVWP2FJC0dQmQRKovG4o9pj8AeLHQuP-pP9JMdAaypAK9RQY0EBiWnY-8HkRNqq6yPskNJAOsCJAKD5GDvTVZvs4ILZzfs-8vHltRAfkBZ6VgaanwX0mJzMRrGzokyMmCnA7mSKSNfdl1guCrNeHG0n-_tVVCqJbhsxZduq6-TTAwgUn8fK3FMtpfm9ojIcYAK81TrcnZpMiWEhJ2WhVlO21BjWOGVxBjoVIK_fuONk9q2rnZVnwA9rHlcn1SdfYO02mBnLW3u0zPK5GN4_g
```

When I try to use this to POST `/api/login/social/jwt/facebook/` I get back a 401 with response 
```
    {
        "detail": "Signature has expired."
    }
```

Any suggestions? Thanks

**Comment by st4lk** [comment]
@BrettStatman 
Please try the [example](https://github.com/st4lk/django-rest-social-auth#example) project. Maybe your issue is caused by front-end code.
Fill free to re-open it if example project doesn't work for you.
