### ISSUE TITLE
Django 2.0 supported ?

### ISSUE THREAD

**Issue by User889** [st4lk/django-rest-social-auth#58]
Hello, when be supported Django2.0 ?

**Comment by st4lk** [comment]
Hi, will work on it soon

**Comment by st4lk** [comment]
It is supported now: [v1.3.0](https://pypi.org/project/rest_social_auth/1.3.0/)
/cc @ultra2mh @yedengbp

**Comment by st4lk** [comment]
Small fix: [v1.3.1](https://pypi.org/project/rest_social_auth/1.3.1/)
