### ISSUE TITLE
Authentication process canceled; ; {'error': 'invalid_grant', 'error_description': 'Malformed code.'}

### ISSUE THREAD

**Issue by vince015** [st4lk/django-rest-social-auth#59]
I am using this for my Google Plus sign in. I am always getting HTTP 400 error: Authentication process canceled; ; {'error': 'invalid_grant', 'error_description': 'Malformed code.'}

I followed all configurations instruction. Google return a token_id and access_token. I tried passing both values in the code parameter but both get the same error. What's your take on this?

**Comment by st4lk** [comment]
@vince015 
Please try [example project](https://github.com/st4lk/django-rest-social-auth#example). It should work.

**Comment by st4lk** [comment]
Fill free to re-open if example project doesn't work for you.

**Comment by hemangsk** [comment]
Hi @st4lk , I'm facing the same issue and I have a bit different architecture than the example project in the sense that my backend and frontend are on separate URLs. I've added the settings:

```
REST_SOCIAL_OAUTH_REDIRECT_URI = '/'
REST_SOCIAL_DOMAIN_FROM_ORIGIN = True
```

I'm getting the ```{'error': 'invalid_grant', 'error_description': 'Malformed code.'}```   returned when using google-oauth2. 

It'll be really great if you can provide some assistance, Thanks :)
