### ISSUE TITLE
Is adding JSON Web Tokens a feature you would consider for this project?

### ISSUE THREAD

**Issue by aabmass** [st4lk/django-rest-social-auth#6]
Hello, just wondering if adding JSON Web Token support to this project is something you would consider in the roadmap. I am using [Satellizer](https://github.com/sahat/satellizer) and Angular, like the example app. However, I am using JWT's with [django-rest-framework-jwt](https://github.com/GetBlimp/django-rest-framework-jwt), which was pretty easy to configure. Would adding JWT endpoints like `/api/login/social/jwt_token/` be a feature you would consider useful upstream? I think this would be nice since Satellizer expects JWT's anyway and could save users some configuration.

I'd be happy to share what I've done.

Thanks!

**Comment by st4lk** [comment]
Hi Aaron!
Sure, it sounds interesting.

**Comment by cleder** [comment]
8-) That is something i'd be interested in as well

**Comment by aabmass** [comment]
What is the best way to handle the dependency on https://github.com/GetBlimp/django-rest-framework-jwt?  It is only required if using JWT's, so I guess its optional? I tried catching the `ImportError`, but the tests failed in my pull request.

**Comment by st4lk** [comment]
As i see, there is an import in views.py:

    from rest_framework_jwt.authentication import JSONWebTokenAuthentication

that can raise an exception, if rest_framework_jwt is not installed

**Comment by st4lk** [comment]
This view is in example_project, so it is ok not to wrap it with `try...except ImportError`. We just need to define dependency for tests, i'll do it soon.

**Comment by aabmass** [comment]
Okay, sounds good!

**Comment by st4lk** [comment]
It is merged now, thanks!
I will push new version to pypi in next couple of days

**Comment by aabmass** [comment]
Awesome! I'll close the issue.

**Comment by st4lk** [comment]
Uploaded [v0.4.0](https://pypi.python.org/pypi/rest_social_auth/0.4.0) to pypi.
