### ISSUE TITLE
we need django 2.0++ support

### ISSUE THREAD

**Issue by ultra2mh** [st4lk/django-rest-social-auth#61]

**Comment by st4lk** [comment]
Hi, will work on it soon

**Comment by yedengbp** [comment]
@st4lk 
What are the main tasks to make it work with Django 2.0+?
I am trying to use it with 2.0+ now. I am wondering that if I can make a quick-and-dirty version for my own tests now.

**Comment by yedengbp** [comment]
@st4lk  
Oh. That's cool. Thanks.

**Comment by st4lk** [comment]
Closing as duplicate of #58
