### ISSUE TITLE
How to include OAuth1 urls?

### ISSUE THREAD

**Issue by ankursharma319** [st4lk/django-rest-social-auth#65]
When I try to do a POST request to `https://localhost:8000/api/login/social/` with form-data `provider=twitter`, I get the 404 error `Not Found: /api/login/social/`.

I suspect the problem is because I have not included the correct url for oauth1 (i.e. twitter).

For facebook (which is oauth2), I did this: `path('api/login/', include('rest_social_auth.urls_token')),` and that is working fine. So can someone tell me what I should include in urls for oauth1?

Thanks

**Comment by st4lk** [comment]
@ankursharma319 
Try to run [example](https://github.com/st4lk/django-rest-social-auth#example) project.
And access it by http://127.0.0.1:8000/ 
It is working for me.

**Comment by st4lk** [comment]
Fill free to re-open if example project doesn't work for you.
