### ISSUE TITLE
Support social-auth-app-django >= 3.1.0,<4.0?

### ISSUE THREAD

**Issue by krnr** [st4lk/django-rest-social-auth#70]
`social-auth-app-django` recently released [version 3.1](https://github.com/python-social-auth/social-app-django/blob/ce15088d2bf04a87eb60a46eb6cbb882060ab45c/CHANGELOG.md#310---2018-10-31) which contains important improvements, which are:

> Updated JSONField.from_db_value signature to support multiple Django versions by accepting just the needed parameters.
> Cleanup username when using email as username

(maybe other enhancements are important for other developers...)

it's a good time to bump [version](https://github.com/st4lk/django-rest-social-auth/blob/master/requirements.txt#L4)

**Comment by st4lk** [comment]
Good spot, thank you.
Will check it soon

**Comment by st4lk** [comment]
Now on pypi: [v1.5.0](https://pypi.org/project/rest_social_auth/1.5.0/)
