### ISSUE TITLE
Twitter oauth1 doesn't work. 

### ISSUE THREAD

**Issue by danilke** [st4lk/django-rest-social-auth#72]
Hello, I'm trying to log in with twitter oauth1, but I'm getting an error: 

```HTTPError at /api/login/social/token/
403 Client Error: Forbidden for url: https://api.twitter.com/oauth/request_token
```
https://github.com/python-social-auth/social-app-django/issues/164 - I think here is the reason.

**Comment by derek-adair** [comment]
Works for me and is resolved by https://github.com/python-social-auth/social-app-django/issues/164

I'd suggest closing this one.

**Comment by st4lk** [comment]
Since https://github.com/python-social-auth/social-app-django/issues/164 is closed and I can't reproduce it - I'm closing it.
