### ISSUE TITLE
Update to social-auth-core to version 3.0.0 to migrate away from Google+ API's

### ISSUE THREAD

**Issue by AnitaGandhi** [st4lk/django-rest-social-auth#73]
From Google:

On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019.

social-auth-core just updated their code base(https://github.com/python-social-auth/social-core/pull/301) to migrate away from Google+ APIs with their 3.0.0 release. Currently django-rest-social-auth only supports social-auth-core >=1.7.0, <2.0.

Can this be updated?

**Comment by st4lk** [comment]
Good catch!
I think yes, we can update the dependency. At least don't have any objections right now, unless 3.0 release has some backward incompatibility that affects django-rest-social-auth.

**Comment by AnitaGandhi** [comment]
Hey.. Just checking in to see if there was any progress on this. Would it be better if I opened a PR to move this forward?

**Comment by st4lk** [comment]
@AnitaGandhi 
Sure, PR is always welcome!

**Comment by st4lk** [comment]
The fix is [v2.0.1](https://pypi.org/project/rest-social-auth/2.0.1/) now.
