### ISSUE TITLE
django-rest-framework-jwt is outdated

### ISSUE THREAD

**Issue by Ernestoo777** [st4lk/django-rest-social-auth#74]
I want to use jwt tokens but as far as I know `django-rest-framework-jwt` doesn't support Django 2.*
Are there problems with using this library in production?

**Comment by jgadelange** [comment]
I created a Pull Request (#76) to implement support for [djangorestframework-simplejwt]. If you have any problems with `django-rest-framework-jwt` you could try that.

[djangorestframework-simplejwt]: https://github.com/davesque/django-rest-framework-simplejwt

**Comment by st4lk** [comment]
@Ernestoo777 @jgadelange 
Deployed to pypi: [v2.1.0](https://pypi.org/project/rest-social-auth/2.1.0/).
