### ISSUE TITLE
Upload current version to PyPI

### ISSUE THREAD

**Issue by phlucas96** [st4lk/django-rest-social-auth#81]
Hi. Is it possible to update the version of this project to include the most recent changes? I want to use it on a project, but the current version (2.0.2) does not include simplejwt integration, which I need. Thanks.

**Comment by st4lk** [comment]
Hi Pedro.
Yes, I'll update the version soon, just want to do some final improvements. It will be published in next couple of days.

**Comment by st4lk** [comment]
@phlucas96 
Deployed to pypi: [v2.1.0](https://pypi.org/project/rest-social-auth/2.1.0/).
