### ISSUE TITLE
LICENSE vs setup.py

### ISSUE THREAD

**Issue by jayvdb** [st4lk/django-rest-social-auth#87]
I am trying to package this for openSUSE, the setup.py says BSD, but the LICENSE file is MIT.

Could you clarify which one you intend, and fix the conflict (or I can submit PRs where I find the problem if I know which one is your intention).

**Comment by st4lk** [comment]
Oops, thanks for spotting this out!

Can you check https://github.com/st4lk/django-rest-social-auth/pull/88, will it be correct now?

**Comment by st4lk** [comment]
I'll deploy new version to pypi soon.

**Comment by jayvdb** [comment]
A merged PR is sufficient for my needs, so dont rush out a release if you are not ready for it.
