### ISSUE TITLE
Adding CORS to backend

### ISSUE THREAD

**Issue by safdarzeeshan** [st4lk/django-rest-social-auth#9]
Hi,
I have separated my Front End (Angular) and Backend (Django using django-rest-social-auth) and are running different servers and have different ports. Because of that I have to take into account cross origin issues. I have enabled CORS on my django backend and my front end is able to set a csrf token for each post. 

I have made sure this works correctly by accessing a post method in my django view that does not use any external library. This method had the @method_decorator(csrf_protect) to ensure it is protected.

I am now trying to authenticate my user which uses your social auth library. I am adding a csrf token. My request is below:

```
POST /api/login/social/session/ HTTP/1.1
Host: mykloudkitchen.com:8000
Connection: keep-alive
Content-Length: 84
Accept: application/json, text/plain, */*
Origin: http://lovetoeat.it:9000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
x-csrftoken: QgnjBRFddxW7pfiC2KbnA92dRIjh6RGi
Content-Type: application/json;charset=UTF-8
Referer: http://lovetoeat.it:9000/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,ar;q=0.6
Cookie: csrftoken=QgnjBRFddxW7pfiC2KbnA92dRIjh6RGi
```

This gives me an error
```
POST http://mykloudkitchen.com:8000/api/login/social/session/ 400 (BAD REQUEST)
```

and in my django console I see the following log
```
Authentication process canceled
Traceback (most recent call last):
  File "/Users/zeeshan/projects/kloud-kitchen/env/lib/python2.7/site-packages/rest_social_auth/views.py", line 108, in post
    user = self.get_object()
  File "/Users/zeeshan/projects/kloud-kitchen/env/lib/python2.7/site-packages/rest_social_auth/views.py", line 142, in get_object
    user = self.request.backend.complete(user=user)
  File "/Users/zeeshan/projects/kloud-kitchen/env/lib/python2.7/site-packages/social/backends/base.py", line 41, in complete
    return self.auth_complete(*args, **kwargs)
  File "/Users/zeeshan/projects/kloud-kitchen/env/lib/python2.7/site-packages/social/utils.py", line 232, in wrapper
    raise AuthCanceled(args[0])
AuthCanceled: Authentication process canceled
[29/Dec/2015 02:48:41] "POST /api/login/social/session/ HTTP/1.1" 400 0
```

Alot of the time 400 errors are due to malformed requests. Is there a specific way to send the csrf token when using the social-auth library?

Any help would be appreciated
Thanks :)

**Comment by safdarzeeshan** [comment]
Turned out it wasn't a cors issue

**Comment by annshress** [comment]
So what was it about? I am having similar issue with CSRF.
