### ISSUE TITLE
Not clear how to use it

### ISSUE THREAD

**Issue by vovkd** [st4lk/django-rest-social-auth#91]
Maybe i've i just missed something from the docs, but how i suppose to use it?
1) First. Get acces token from oauth provider
2) Send this token to /social/token_user/
3) Backend will authenticate user and return some data

Is it correct?

I've tested this with vk.com:
1) created vk app
2) received auth code from vk.com
3) POSTed it to /social/token_user/ 
  provider=vk-oauth2 
  code=xxxxxxxx
4) received (social_core.exceptions.AuthForbidden: Your credentials aren't allowed)
What i do wrong? or maybe i've misread something in the docs?

**Comment by st4lk** [comment]
Haven't looked into details yet, but strictly speaking this is not correct:
> First. Get acces token from oauth provider

Current util expect [code](https://tools.ietf.org/html/rfc6749#section-1.3.1) as input, not [access token](https://tools.ietf.org/html/rfc6749#section-1.4)

**Comment by vovkd** [comment]
My bad. Yes, i mean "auth code". As i've found out problem was with Twitter itself. Thanks.
