### ISSUE TITLE
Custom user problem

### ISSUE THREAD

**Issue by d0rift1** [st4lk/django-rest-social-auth#96]
when using a custom user model (AbstractBaseUser) this error appears 
AssertionError: The field 'user_permissions' was included on serializer UserSerializer in the 'exclude' option, but does not match any model field. 
 because of the        
 exclude = (
            'is_staff', 'is_active', 'date_joined', 'password', 'last_login', 'groups', 'is_superuser',
 )
in the UserSerializer
if someone know how to override UserSerializer please tell me.

**Comment by eelectronn** [comment]
I'm wondering if you did end up finding the solution to this?
