### ISSUE TITLE
I don't see how to set the redirect url in the third login platform?

### ISSUE THREAD

**Issue by rootgrandfather** [st4lk/django-rest-social-auth#99]
Authentication process canceled; ; {'error': 'redirect_uri_mismatch', 'error_code': 21322, 'request': '/oauth2/access_token',

**Comment by hexmo** [comment]
For anyone looking into this issue, all I had to do was pass the redirect_url in the body.

![image](https://github.com/st4lk/django-rest-social-auth/assets/35497915/5aff78ab-829a-4cf4-a6df-888e59b83802)
